# Generated by Django 2.0.5 on 2018-05-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_content', models.CharField(max_length=2048)),
                ('create_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField(null=True)),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
